LICENSE
s2i/Dockerfile
s2i/LICENSE
s2i/README.md
s2i/action.yml
s2i/entrypoint.sh

Adds the first GitHub Action (for building container images with s2i) to the repo!

Add S2I Action

---

confbatstest/Dockerfile
confbatstest/README.md
confbatstest/action.yml
confbatstest/entrypoint.sh

action to run BATS tests which execute conftest.
will be used by CoP repos to check yaml/json is valid.
cc @pabrahamsson @tylerauerbeck

Added action to execute bats file which includes conftest policys

---

confbatstest/Dockerfile

Adds helm to the image, so can process helm charts

Added helm to confbats

---

.github/PULL_REQUEST_TEMPLATE.md

Added PR template, based on what other repos use

Added github pr template

---

confbatstest/Dockerfile
confbatstest/README.md
confbatstest/action.yml

Added jq/yq which are needed to process/split JSON/YAML test inputs.
See: https://github.com/redhat-cop/github-actions/pull/10

Added jq/yq to confbatstest

---

.github/workflows/confbatstest.yaml
README.md
confbatstest/_test/conftest.sh
confbatstest/_test/template.yml

Adds a workflow which tests the local action. The idea being, future PRs are auto tested
See action output.

Added workflow to test confbatstest

---

README.md

Just adding some initial structure and README content around adding example workflows here as well
Nothing to test, just README updates.

Update README / repo structure

---

OWNERS

Since I am the main contributor to the confbatstest action, would be nice to be able to review/approve future changes.

Added garethahealy to owners file

---

confbatstest/README.md

Added ci badge to conftest readme

---

confbatstest/Dockerfile

The original base was due to copy+paste of the s2i action. There is no need for this action to be based on the docker base, so have moved to ubi8-minimal
Check test action output.

Updated base to use ubi8 for confbatstest

---

confbatstest/README.md
confbatstest/action.yml
confbatstest/entrypoint.sh

Adds a json input field, which allows for different policies to be pulled in
See test action output (https://github.com/redhat-cop/github-actions/pull/14/checks?check_run_id=787601620)

Added policy array for confbatstest

---

.github/workflows/s2i.yaml

Added ci test for s2i. Before this is merged, the following needs creating:
- quay repo under: redhat-cop/github-actions-s2i
- quay username/password creds adding as a secret to this repo

Added s2i workflow test

---

.github/workflows/redhat-csp-download.yaml
README.md
redhat-csp-download/Dockerfile
redhat-csp-download/README.md
redhat-csp-download/action.yml
redhat-csp-download/ansible/download.yml
redhat-csp-download/ansible/requirements.txt
redhat-csp-download/ansible/requirements.yml
redhat-csp-download/entrypoint.sh

Adds an action which uses redhat-csp-download
Check test action output which will do a partial test - it requires a username/password secret (_which I've created_) for a full test on master branch
- https://github.com/garethahealy/github-actions/runs/806930812?check_suite_focus=true

Added redhat-csp-download action

---

confbatstest/Dockerfile
confbatstest/entrypoint.sh
redhat-csp-download/Dockerfile
redhat-csp-download/entrypoint.sh

Tidy up bash (fixed shellcheck warnings) and added safety checks to make sure things that are requested to be installed, are. Also added a check to validate params that are json
Action is green.

Added safety checks and cleaned up bash for confbatstest and redhat-csp-download

---

.github/workflows/set-helm-version.yaml
set-helm-version/Dockerfile
set-helm-version/Pipfile
set-helm-version/Pipfile.lock
set-helm-version/README.md
set-helm-version/_test/Chart.yaml
set-helm-version/action.yml
set-helm-version/entrypoint.py
set-helm-version/requirements.txt

Adds an action which, given a Helm chart, lets you update the chart and app versions in preparation for an automatic release.
Create a GitHub workflow on a repo with a Helm chart which uses the action as described in the README

Set Helm chart version

---

.github/workflows/confbatstest.yaml
confbatstest/Dockerfile
confbatstest/README.md
confbatstest/action.yml
confbatstest/entrypoint.sh

Adds a new option, to allow for the base tools to be executed. i..e.: konstraint docs or conftest push
Action green!

Added "raw" option to confbatstest

---

confbatstest/Dockerfile

Added opa binary and upgraded versions of conftest, helm and oc
Action stays green

Added opa binary and upgraded versions of conftest, helm and oc for confbatstest

---

chart-repo-pr-action/README.md

Making small adjustment to chart-repo-pr-action readme. Needed to update the reference to redhat-cop/github-actions/chart-repo-pr-action@master

updating chart-repo-pr-action usage documentation

---

confbatstest/Dockerfile

Updates versions to tools
Check the pipeline stays green

Updated versions to latest for confbatstest

---

confbatstest/Dockerfile

Updated versions

---

github-dispatches/Dockerfile
redhat-csp-download/Dockerfile

updated base image to latest ubi

---

README.md

updated readme to include current actions

---

s2i/README.md

Since the redhat-actions repo also provides an s2i, which works on multiple platforms, think we should point people to that one.

added link to rh-actions s2i

---

confbatstest/Dockerfile

needed by: https://github.com/redhat-cop/rego-policies/pull/160
github action goes green

upgraded opa version for confbatstest

---

confbatstest/Dockerfile

needed by: https://github.com/redhat-cop/bats-library/pull/30
Everything goes green!

Added bc to confbatstest

---

OWNERS

Only one merger in EMEA makes for slow feedback loops.
Provide commands/steps to test this PR.

🐦 FIX - too few approvers 🐦

---

.github/workflows/redhat-csp-download.yaml
redhat-csp-download/Dockerfile
redhat-csp-download/README.md
redhat-csp-download/ansible/download.yml
redhat-csp-download/ansible/requirements.yml
redhat-csp-download/entrypoint.sh

action is failing, pip upgrade should solve
green CI

added pip upgrade to solve action failing

---

disconnected-csv/Dockerfile
disconnected-csv/tests/sample-clusterserviceversion.yaml

Limit user actions for disconnected CSV action to resolve #48 

Limit user actions for disconnected CSV action

---

.github/workflows/kyverno-cli.yaml
kyverno-cli/Dockerfile
kyverno-cli/README.md
kyverno-cli/_test/kyverno.sh
kyverno-cli/_test/namespace.yaml
kyverno-cli/_test/policy.yaml
kyverno-cli/action.yml
kyverno-cli/entrypoint.sh

added an action to run `kyverno` (bit like conftest)
- https://kyverno.io
action goes green

added v1 of kyverno-cli

---

confbatstest/README.md

removed deprek8ion as its an archived / deprecated project now

---

.github/workflows/confbatstest-build.yaml
confbatstest/Dockerfile_build
confbatstest/Dockerfile_tmp_runnable
confbatstest/action.yml

part1: build and push image to ghcr. once this is merged, will know if the pushing works, can then open another pr to switch the action to use the `Dockerfile_tmp_runnable`
green ci

added action to pre-build docker image for confbatstest

---

OWNERS

removed tyler as hes left RH

---

.github/workflows/confbatstest-build.yaml

$subject
CI goes green once merged onto master

added version tag to build for confbatstest

---

.github/dependabot.yaml

added dependabot for github actions

---

s2i/action.yml

gives a hint to users that they should move onto the redhat-actions one.

added deprecated message to main param

---

chart-repo-pr-action/Dockerfile

upgraded chartrepo base image

---

confbatstest/Dockerfile_build
kyverno-cli/Dockerfile_build

upgraded kyverno versions

---

s2i/Dockerfile
s2i/entrypoint.sh

$subject
red ci as action should fail

added fail as this action has been deprecated for a while

---

disconnected-csv/Dockerfile
disconnected-csv/add_related_image.py

Upgrade ruamel.yaml configurations in disconnected-csv action for latest version to resolve #82 

Upgrade ruamel.yaml configurations for latest version

---

.github/workflows/confbatstest-build.yaml
.github/workflows/github-dispatches-build.yaml
.github/workflows/kyverno-cli-build.yaml
.github/workflows/redhat-csp-download-build.yaml
chart-repo-pr-action/Dockerfile
renovate.json

added renovate comment for testing

---

renovate.json

dont pin digests for skopeo

---

confbatstest/Dockerfile_build

bumping konstraint version
